# Project: Parking_Lot_Management_System
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o src/billing.o src/parking.o src/utils.o
LINKOBJ  = main.o src/billing.o src/parking.o src/utils.o
LIBS     = -L"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/include" -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/include" -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/LEGION 5 PRO 2021/OneDrive/Desktop/Introduction to C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Parking_Lot_Management_System.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

src/billing.o: src/billing.c
	$(CC) -c src/billing.c -o src/billing.o $(CFLAGS)

src/parking.o: src/parking.c
	$(CC) -c src/parking.c -o src/parking.o $(CFLAGS)

src/utils.o: src/utils.c
	$(CC) -c src/utils.c -o src/utils.o $(CFLAGS)
