# Project: Parking_Lot_Management_System
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o src/billing.o src/parking.o src/utils.o src/auth.o src/fileio.o src/report.o
LINKOBJ  = main.o src/billing.o src/parking.o src/utils.o src/auth.o src/fileio.o src/report.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"

BIN      = Parking_Lot_Management_System.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

src/billing.o: src/billing.c
	$(CC) -c src/billing.c -o src/billing.o $(CFLAGS)

src/parking.o: src/parking.c
	$(CC) -c src/parking.c -o src/parking.o $(CFLAGS)

src/utils.o: src/utils.c
	$(CC) -c src/utils.c -o src/utils.o $(CFLAGS)

src/auth.o: src/auth.c
	$(CC) -c src/auth.c -o src/auth.o $(CFLAGS)

src/fileio.o: src/fileio.c
	$(CC) -c src/fileio.c -o src/fileio.o $(CFLAGS)

src/report.o: src/report.c
	$(CC) -c src/report.c -o src/report.o $(CFLAGS)
